using System.Text.Json;
using MapCore.Models;

namespace MapCore.Services;

public static class ExportService
{
    public static void ExportProject(MapProject project, string outputDirectory)
    {
        Directory.CreateDirectory(outputDirectory);

        string? mapFile = null;
        if (!string.IsNullOrWhiteSpace(project.SourceFilePath) && File.Exists(project.SourceFilePath))
        {
            var sourceIsHtmlMap = project.SourceConfig.TryGetValue("source_type", out var sourceType)
                                  && sourceType.Equals("html_map_data", StringComparison.OrdinalIgnoreCase);
            var sourceExtension = Path.GetExtension(project.SourceFilePath);
            if (sourceIsHtmlMap || sourceExtension.Equals(".html", StringComparison.OrdinalIgnoreCase)
                                 || sourceExtension.Equals(".htm", StringComparison.OrdinalIgnoreCase))
            {
                mapFile = "map.html";
                File.Copy(project.SourceFilePath, Path.Combine(outputDirectory, mapFile), overwrite: true);
            }
        }

        var safeConfig = project.SourceConfig
            .Where(pair => pair.Key.StartsWith("hmap3_", StringComparison.OrdinalIgnoreCase)
                           || pair.Key.Equals("mg_name", StringComparison.OrdinalIgnoreCase))
            .ToDictionary(pair => pair.Key, pair => pair.Value, StringComparer.OrdinalIgnoreCase);

        var panoramaDirectory = Path.Combine(outputDirectory, "panoramas");
        var panoramaFiles = new List<string>();
        if (project.PanoramaFiles.Count > 0)
        {
            Directory.CreateDirectory(panoramaDirectory);
            for (var i = 0; i < project.PanoramaFiles.Count; i++)
            {
                var sourcePath = project.PanoramaFiles[i];
                if (!File.Exists(sourcePath))
                {
                    throw new FileNotFoundException("Файл панорами не знайдено.", sourcePath);
                }

                var fileName = $"{i + 1:D2}-{Path.GetFileName(sourcePath)}";
                File.Copy(sourcePath, Path.Combine(panoramaDirectory, fileName), overwrite: true);
                panoramaFiles.Add($"panoramas/{fileName}");
            }
        }

        var manifest = new
        {
            version = 1,
            name = project.Name,
            generatedAtUtc = DateTime.UtcNow,
            mapFile,
            config = safeConfig,
            markers = project.Markers.Select(m => new
            {
                m.Name,
                x = m.X,
                y = m.Y,
                m.Note,
                heading = m.Heading,
                pitch = m.Pitch
            }),
            panoramas = panoramaFiles
        };

        var json = JsonSerializer.Serialize(manifest, new JsonSerializerOptions { WriteIndented = true });
        File.WriteAllText(Path.Combine(outputDirectory, "manifest.json"), json);

        var readme = "# " + project.Name + "\n\n" +
                     "This package was generated by the MapBuilder tool for GitHub-based map distribution.\n" +
                     "The Android client downloads the manifest and uses it to render markers and 360 photos.\n";
        File.WriteAllText(Path.Combine(outputDirectory, "README.md"), readme);
    }
}
